version: "3.7"

services:
  client:
    image: node:14-alpine
    command: sh -c "yarn install && yarn start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./client:/app

  nats:
    entrypoint: "/nats-server -c nats-server.conf -DV"
    image: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
