version: "3.7"

services:
  client:
    image: node:14-alpine
    command: sh -c "yarn install && yarn start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./client:/app

  api-gateway:
    image: node:14-alpine
    command: sh -c "yarn install && yarn start:dev & npx firebase emulators:start --import=./firebase-emulator-data --export-on-exit"
    ports:
      - 5000:5000
      - 9005:9005
      - 9098:9098
      - 9099:9099
    working_dir: /app
    volumes:
      - ./api-gateway:/app
    environment:
       FIREBASE_AUTH_EMULATOR_HOST: localhost:9099
       NODE_ENV: development
       PORT: 5000

  nats:
    entrypoint: "/nats-server -c nats-server.conf -DV"
    image: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
