version: "3.7"

services:
  client:
    image: 776739177330.dkr.ecr.ap-southeast-1.amazonaws.com/peerprep/client
    ports:
      - 80:80
    depends_on:
      - "api-gateway"
    x-aws-autoscaling:
      min: 0.25
      max: 2
      cpu: 75

  api-gateway:
    image: 776739177330.dkr.ecr.ap-southeast-1.amazonaws.com/peerprep/api-gateway
    env_file: ./.env.production
    depends_on:
      - "nats"
      - "redis"
    x-aws-autoscaling:
      min: 0.25
      max: 2
      cpu: 75

  collaboration-service:
    image: 776739177330.dkr.ecr.ap-southeast-1.amazonaws.com/peerprep/collaboration-service
    env_file: ./.env.production
    depends_on:
      - "nats"
    x-aws-autoscaling:
      min: 0.25
      max: 2
      cpu: 75

  practice-service:
    image: 776739177330.dkr.ecr.ap-southeast-1.amazonaws.com/peerprep/practice-service
    command: sh -c "NODE_ENV=production yarn run typeorm:migrate && NODE_ENV=production yarn run seed && yarn start:prod"
    env_file: ./.env.production
    depends_on:
      - "nats"
      - "practice-service-postgres"
    x-aws-autoscaling:
      min: 0.25
      max: 2
      cpu: 75

  code-runner-service:
    image: 776739177330.dkr.ecr.ap-southeast-1.amazonaws.com/peerprep/code-runner-service
    depends_on:
      - "nats"
    x-aws-autoscaling:
      min: 0.25
      max: 2
      cpu: 75

  practice-service-postgres:
    env_file: ./.env.production
    image: postgres:12
    volumes:
      - practice-service-postgres:/var/lib/postgresql/data
    deploy:
      replicas: 1

  nats:
    image: nats
    deploy:
      replicas: 1

  redis:
    image: redis:alpine
    deploy:
      replicas: 1

volumes:
  practice-service-postgres:
