name: Deploy to Amazon ECS

on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: peerprep/api-gateway
  ECS_SERVICE: cs3219-project-ay2122-2122-s1-g34-ApigatewayService-Ymx9PonEnpdo
  ECS_CLUSTER: cs3219-project-ay2122-2122-s1-g34
  ECS_TASK_DEFINITION: .aws/task-definition.json

  CONTAINER_NAME: api-gateway

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create .env.production
        env:
          ENV: ${{ secrets.ENV }}
        run: |
          echo "$ENV" > .env.production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker Build
        id: docker-build
        uses: docker/build-push-action@v2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        with:
          context: ./api-gateway
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Push image to Amazon ECR
        id: push-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        working-directory: ./api-gateway
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Install Docker Compose CLI
        run: |
          curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh

      - name: Create an ecs context
        run: |
          docker context create ecs ecscontext --from-env

      - name: Deploy to ECS
        run: |
          docker --context ecscontext compose -f production.yml up
